set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)

set(VCPKG_CMAKE_SYSTEM_NAME Darwin)
set(VCPKG_CMAKE_SYSTEM_VERSION 13.0)
set(VCPKG_CMAKE_OSX_DEPLOYMENT_TARGET 13.0)

# Set the minimum macOS version for all dependencies
set(CMAKE_OSX_DEPLOYMENT_TARGET 13.0)
set(VCPKG_OSX_DEPLOYMENT_TARGET 13.0)
